-- Blog CMS — Posts
--
-- IMPORTANT (hybrid architecture — see BLOG-README.md and the project's own
-- architecture decision): this table holds ONLY posts created through the
-- new CMS. The 79 existing posts imported from WordPress remain exactly as
-- static files generated by scripts/build-post-pages.py from
-- data/blog-data.json — they are NOT duplicated into this table, and this
-- table does not need to know about them. blog-cms/public/router.php only
-- ever receives a request when Apache found no matching static file/dir for
-- that URL, so there is no runtime overlap between the two systems.
--
-- category_id + slug together reproduce the site's real existing URL shape:
-- /<category_slug>/<post_slug>/ — this is what makes a CMS-created post look
-- identical, URL-wise, to a legacy static one.

CREATE TABLE IF NOT EXISTS blog_posts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    excerpt VARCHAR(500) DEFAULT NULL,
    content MEDIUMTEXT NOT NULL,
    featured_image_id INT UNSIGNED DEFAULT NULL,
    category_id INT UNSIGNED NOT NULL,
    author_id INT UNSIGNED NOT NULL,
    status ENUM('draft', 'published', 'scheduled', 'archived') NOT NULL DEFAULT 'draft',
    published_at DATETIME DEFAULT NULL,
    scheduled_at DATETIME DEFAULT NULL,

    -- SEO
    meta_title VARCHAR(255) DEFAULT NULL,
    meta_description VARCHAR(500) DEFAULT NULL,
    focus_keyword VARCHAR(150) DEFAULT NULL,
    canonical_url VARCHAR(500) DEFAULT NULL,
    robots_index ENUM('index', 'noindex') NOT NULL DEFAULT 'index',
    robots_follow ENUM('follow', 'nofollow') NOT NULL DEFAULT 'follow',
    og_title VARCHAR(255) DEFAULT NULL,
    og_description VARCHAR(500) DEFAULT NULL,
    og_image VARCHAR(500) DEFAULT NULL,
    twitter_title VARCHAR(255) DEFAULT NULL,
    twitter_description VARCHAR(500) DEFAULT NULL,
    twitter_image VARCHAR(500) DEFAULT NULL,

    -- Misc
    reading_time SMALLINT UNSIGNED DEFAULT NULL,
    allow_comments TINYINT(1) NOT NULL DEFAULT 0,
    schema_type VARCHAR(50) NOT NULL DEFAULT 'BlogPosting',
    -- Internal content-completeness score computed by includes/seo.php from
    -- this post's own fields (title/meta/content-length/image/etc present) —
    -- NOT a Google ranking signal or a real Google score of any kind. Shown
    -- in the admin UI labeled "Content checklist score" for exactly that
    -- reason (see includes/seo.php's calculate_seo_score() docblock).
    seo_score TINYINT UNSIGNED DEFAULT NULL,

    -- Preview access without a predictable public URL — see includes/blog_functions.php
    preview_token VARCHAR(64) DEFAULT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY uq_blog_posts_slug (slug),
    INDEX idx_blog_posts_status (status),
    INDEX idx_blog_posts_published_at (published_at),
    INDEX idx_blog_posts_category_id (category_id),
    INDEX idx_blog_posts_author_id (author_id),
    INDEX idx_blog_posts_preview_token (preview_token),

    CONSTRAINT fk_blog_posts_category FOREIGN KEY (category_id) REFERENCES blog_categories(id) ON DELETE RESTRICT,
    CONSTRAINT fk_blog_posts_author FOREIGN KEY (author_id) REFERENCES blog_users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- featured_image_id -> blog_media.id is added as a separate ALTER in
-- 004_create_blog_media.sql, once blog_media exists (avoids a forward
-- reference / table-creation-order problem between the two).
