<?php
/**
 * Dynamic sitemap for CMS-managed posts ONLY — published posts, nothing
 * else (no drafts, no admin URLs, no revisions). Kept SEPARATE from
 * sitemap.xml/sitemap-blog.xml (which list the 79 existing static posts and
 * are regenerated by Python scripts) rather than merging into them, since
 * those are static files this PHP script can't safely rewrite mid-request.
 * Referenced as an additional Sitemap: line in robots.txt (additive, see
 * DEPLOYMENT.md) — search engines are fine reading multiple sitemaps.
 */

declare(strict_types=1);

require_once __DIR__ . '/../includes/blog_functions.php';

header('Content-Type: application/xml; charset=utf-8');

$pdo = blog_db();
$stmt = $pdo->query(
    "SELECT p.slug, p.updated_at, c.slug AS category_slug
       FROM blog_posts p
       JOIN blog_categories c ON c.id = p.category_id
      WHERE p.status = 'published' AND p.published_at <= NOW()
      ORDER BY p.published_at DESC"
);
$posts = $stmt->fetchAll();

echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";
foreach ($posts as $p) {
    $loc = 'https://theomegagroup.in/' . $p['category_slug'] . '/' . $p['slug'] . '/';
    $lastmod = substr($p['updated_at'], 0, 10);
    echo '  <url><loc>' . htmlspecialchars($loc, ENT_XML1) . '</loc><lastmod>' . $lastmod . '</lastmod>'
        . '<changefreq>monthly</changefreq><priority>0.6</priority></url>' . "\n";
}
echo '</urlset>' . "\n";
